### ISSUE TITLE
Rework adding and removing tabs

### ISSUE THREAD

**Issue by awangg** [awangg/NewTab#10]
Removing is broken, probably due to remnant code from when it was outside the settings. Rewrite the entire file.

**Comment by andrewward2001** [comment]
@awangg are you working on this now with the new settings or is this still me?

**Comment by awangg** [comment]
@andrewward2001 You should probably do it since you made the new settings

**Comment by andrewward2001** [comment]
but you made the new settings

**Comment by awangg** [comment]
Alright

**Comment by awangg** [comment]
Adding works

**Comment by awangg** [comment]
Removing works -- check all the jquery if u can @andrewward2001
