### ISSUE TITLE
Repair JSONs

### ISSUE THREAD

**Issue by awangg** [awangg/NewTab#12]
The way we are calling and storing JSONs is a big nono.

**Comment by andrewward2001** [comment]
This should be pretty much fixed. Pls add any issues that arise from the fixes.

**Comment by awangg** [comment]
I think I found it -- the $.getJSON call is not running or something

**Comment by awangg** [comment]
@andrewward2001 the damn variable in the storage.sync.get is wrong

**Comment by awangg** [comment]
Storage variable was incorrect but I fixed it
